costmap:
   global_frame: "map"
   robot_base_frame: "world"
   map_topic: /map

   subscribe_to_updates: false
   always_send_full_costmap: true
   rolling_window: false

   transform_tolerance: 1.0
   resolution: 0.05

   robot_radius: 0.01
   footprint: [[0.05,0.05], [0.05,-0.05], [-0.05, -0.05], [-0.05, 0.05]]
   footprint_padding: 0.001

   inflation_layer: 
      cost_scaling_factor: 2
      enabled: true
      inflate_unknown: false
      inflation_radius: 3.0

   static_layer:
      unknown_cost_value: -1
      lethal_cost_threshold: 100

   plugins:
      - {name: static_layer, type: "costmap_2d::StaticLayer"}
      - {name: inflation_layer, type: 'costmap_2d::InflationLayer'}
  