name: Build for Ubuntu 20.04 and ROS noetic

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: ros:noetic

    defaults:
      run:
        shell: bash -leo pipefail {0}

    steps:
      - name: Create catkin workspace
        run:
          mkdir $GITHUB_WORKSPACE/catkin_ws/src -p ;
          cd $GITHUB_WORKSPACE/catkin_ws;
          source /opt/ros/noetic/setup.bash;
          catkin_make;

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          path: catkin_ws/src/
          
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
        with:
           languages: cpp
           
      - name: Build package
        run: |
          export DEBIAN_FRONTEND=noninteractive
          cd $GITHUB_WORKSPACE/catkin_ws;
          source /opt/ros/noetic/setup.bash;
          apt update && rosdep update && rosdep install --from-paths src/ -y -r;
          catkin_make;

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v1
        with:
          path: catkin_ws/src/

        
